# -*- coding: utf-8 -*-
"""v0.95 全量建卡：63 个待建叶 → 24 张新建域卡 + 3 叶挂已建域 + 12 兜底叶（E99）。
纪律：全部参数为 AI 提议草案（2026-09-10），逐项待人工确认后生效（治理规则同《路线TRL更新提议》）；
指标只给公开参考值（ctx 列），正式基线一律 null 待登记——不编造阈值。
字段：
  trl_routes: [(路线, TRL带, 依据(草案))]
  metrics:    [(指标, 单位, 公开参考(非登记基线))]  —— 正式基线 null
  bottlenecks:[(id, 中文, CORE/SECONDARY, 关联评价族)]
  matrix:     {card_id: (标记★/○/—, 要点)}  —— 12 张通用卡沿用，不新设卡
  priority:   近期待建（《行业图景对照》三）/ 覆盖建卡

v0.97（2026-09-14）新增 DOMAIN_DECISION_RULES：先切正文域，再按研究对象/最终产品/
关键技术瓶颈裁决主域；专属子域与排他路线优先于父域和能源来源背景。
"""

# v0.97 主域裁决。字段：规则ID、场景、强制规则、证据要求、典型纠错。
DOMAIN_DECISION_RULES = [
    ("D-G01", "正文域净化", "领域计分只使用标题对应主文块；导航、推荐、广告、版权、历史回顾、下一篇/相关阅读全部剔除",
     "保存主文起止位置和被移除块，污染词不得贡献标题/正文/主体/指标分", "避免正文杂质把光伏文误判为核电"),
    ("D-G02", "主对象优先级", "研究对象/最终产品与用途 > 关键瓶颈部件/工艺 > 系统资产 > 能源来源/原料背景 > 偶然提及",
     "至少给出主语、动作、技术对象和瓶颈证据位置；不能只按词频", "风电供电制氢且难点在电解槽→氢基能源"),
    ("D-G03", "专属叶优先", "命中专属技术路线并满足必要证据时，专属叶优先于宽泛父域/应用域；父域只能做次域",
     "专属路线词+对象或指标至少二项；避免单关键词误吸附", "液流/熔盐/重力/飞轮/压缩空气不被笼统储能系统覆盖"),
    ("D-G04", "排他路线标题", "标题明确出现专属路线且正文未否定时，给予主域强先验；其他域需有更强主对象证据才能覆盖",
     "排他词必须在标题或主文首段，且不是列表/背景", "二氧化碳储能、压缩空气储能、海水制氢等"),
    ("D-G05", "器件用途裁决", "同一材料跨域时按器件功能和最终用途归域，材料名称不得决定领域",
     "识别器件类型、输出功能、应用场景", "钙钛矿 LED/发光器件→光电器件 E99，不归光伏"),
    ("D-G06", "耦合项目裁决", "风光储氢等耦合报道按被解决的核心难点与主要产物判主域，电源/配套设施做次域标签",
     "主产物、核心技术问题、主要指标三者至少二者一致", "电解槽应对波动电流→氢基能源；风电仅电源背景"),
    ("D-G07", "电芯与系统分层", "电芯化学体系、材料、循环/能量密度归电池技术域；PCS/EMS/系统集成/电站/并网/时长归储能系统或专属储能叶",
     "对象粒度+系统级/电芯级指标", "详细储能技术介绍不因只出现一次『储能』而低领域分"),
    ("D-G08", "英文文献匹配", "论文标题、摘要和正文均执行中英文同义词与化学式匹配，标题未命中不构成低置信",
     "记录规范化术语、命中位置和载体身份", "Nanocrystal-tailored…全钙钛矿叠层论文按标题+摘要判光伏"),
    ("D-G09", "跨界战略主题", "数据中心、AI 算力能源、行业脱碳等不是自动域外；有明确供电、储能、热管理、绿电直供或减排技术对象时归对应技术域",
     "战略主题词+具体能源技术对象/指标", "数据中心分析可归储能/电网/电力系统，主题词本身不加分"),
    ("D-G10", "域外复核", "判域外前必须通读正文，检查行业图景125条路径、AI与通用技术分支、英文同义表达、对象层级和允许新增的稳定领域；不得读取D/T分",
     "记录主要对象、排除过的候选路径、正文片段和明确域外原因", "正文明确为新路线 → 新增领域并直接纳入通用评分机制"),
]

# 专属路线与父域互斥/优先关系（v0.97，供运行时判域与回归测试共用）。
DOMAIN_PRIORITY_RULES = [
    ("liquid_flow_battery", "storage_system", "液流电池|全钒液流|铁铬液流|锌溴液流|flow battery", "命中路线+电解液/堆/时长/容量之一→液流主域"),
    ("molten_salt_thermal_storage", "storage_system", "熔盐储热|molten salt thermal storage", "储热本体主域；若为光热电站整体，CSP 可主域"),
    ("mechanical_storage", "storage_system", "重力储能|飞轮储能|抽水蓄能", "专属路线主域，储能系统次域"),
    ("caes", "storage_system", "压缩空气储能|CAES|二氧化碳储能", "专属路线主域，系统集成仅次域"),
    ("hydrogen_based_energy", "wind_power", "制氢|电解槽|绿氢|海水制氢", "若主产物为氢或瓶颈在电解槽，氢基能源主域"),
    ("optoelectronic_device", "pv_photovoltaic", "钙钛矿LED|钙钛矿发光二极管|PeLED|perovskite LED", "光电器件主域，排除光伏"),
]

# 挂已建域的双视角叶（v0.93 已登记裁定）：叶名 → domain_id
EXISTING_DOMAIN_EXTRA_LEAVES = {
    "固态电池": "li_battery",          # 树中为锂电平行叶；维持固态=锂电域内路线（差异已登记）
    "甲醇": "hydrogen_based_energy",   # 平台化工品|甲醇 与 氢基能源|绿甲醇 同物双视角 → 挂氢基能源域
    "氨": "hydrogen_based_energy",     # 同上（绿氨）
}

# 12 个『其它/其他』兜底叶：按语义定义和同级排除条件裁决，不用 D 值自然归属；评分使用通用类型机制。
E99_LEAVES = ["其它体系", "其它电池体系", "其它储能技术", "其他化学能储能", "其他储热技术",
              "其它能量分配技术", "其它平台化工品", "其它大宗化工产品", "其它金属产业",
              "其它无机非金属", "其他发电技术", "其他环境治理"]

EXPAND_DOMAINS = [
    # ================= 能量转化（16 域） =================
    {
        "id": "E01", "slug": "csp_solar_thermal", "name": "光热发电（CSP）", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能源测|一次能源转化|太阳能转化|光热", "leaves": ["光热"],
        "priority": "近期待建",
        "core": "光热|聚光|塔式|槽式|线菲|定日镜|熔盐塔|CSP|集热",
        "ext": "吸热器|镜场|导热油|熔盐罐|光热电站|光热+光伏|聚光比",
        "stage_words": "示范电站|并网|满发|集热调试|储热时段",
        "actors": "首航高科、中控太阳能、上海电气、东方电气、兰州大成（草案，待补充）",
        "scale_anchor": "100MW 级示范电站为域量级参考（草案）；典型储热 8-12h",
        "require": "光热/聚光/塔式/槽式词 + 电站指标（MW、储热时长 h、年利用小时数）",
        "confuse": [("光伏", "聚光集热发电 vs 光电转换，技术路线不同", "路线词区分"),
                    ("储热（E12）", "熔盐储热本体归储热域；光热电站整体（含配储）归本域", "对象粒度")],
        "trl_routes": [("塔式熔盐", "6-8", "首批 100MW 级示范商运 + 规模化基地在建（草案）"),
                       ("槽式/线菲", "7-8", "成熟示范路线（草案）")],
        "frontier": "量产/定型", "frontier_desc": "规模化光热基地（光热+光伏一体化）建设为前沿；单站示范已商运（草案）",
        "metrics": [("光热电站光电转换效率", "%", "塔式设计值约 15-18（公开参考，正式基线 null）"),
                    ("年等效利用小时数", "h", "配储后约 4000-6000（公开参考）")],
        "bottlenecks": [("csp_cost", "单位投资成本（vs 光伏+储能）", "CORE", "project_facility_state,financing_capital_state"),
                        ("salt_freeze", "熔盐防凝与高温吸热器材料", "SECONDARY", "engineering_validation_state")],
        "financing_anchor": "以项目融资/EPC 为主，股权轮少见（草案 null 待登记）",
        "policy_hot": "光热示范与规模化基地名单、沙戈荒大基地配储要求（草案）",
        "matrix": {"card_tech": ("○", "吸热器/熔盐材料命题"), "card_validation": ("★", "示范电站满发时数验证"),
                   "card_project": ("★", "光热基地/示范项目"), "card_product": ("○", "定日镜/集热器装备"),
                   "card_enterprise": ("—", ""), "card_production": ("○", "电站运行数据"),
                   "card_supply": ("—", ""), "card_financing": ("○", "项目融资"),
                   "card_procurement": ("○", "EPC/镜场招标"), "card_talent": ("—", ""),
                   "card_market": ("○", "示范项目电价"), "card_policy": ("★", "大基地配储/示范名单")},
    },
    {
        "id": "E02", "slug": "hydro_power", "name": "水电", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能源测|一次能源转化|水电", "leaves": ["水电"],
        "priority": "覆盖建卡",
        # 2026-09-18 复核补丁：英文源（ess-news 等）水电词并入，避免 Statkraft 类英文标题漏判
        "core": "水电|水电站|水轮机|抽水蓄能|流域开发|梯级电站|hydropower|hydroelectric|pumped storage|pumped-storage",
        "ext": "装机|出力|库容|机组|引水发电|水电灵活性改造|hydropower reservoir|hydro turbine|reservoir expansion|水电扩容|扩机",
        "stage_words": "核准|开工|蓄水|首台机组|投产|扩容|扩建|begins construction|expansion",
        "actors": "三峡集团、长江电力、华能水电、国投电力、雅砻江水电（草案）",
        "scale_anchor": "常规大水电 GW 级、抽蓄单站 1200MW 级为量级参考（草案）",
        "require": "水电/流域/机组词 + 指标（GW 装机、利用小时、机组 MW）",
        "confuse": [("机械储能（E14）", "抽水蓄能在情报上多随储能/电力市场议题；树中无独立叶，本域收编", "对象粒度")],
        "trl_routes": [("常规水电", "9", "成熟产业（草案）"),
                       ("抽水蓄能", "8-9", "成熟，大规模建设期（草案）")],
        "frontier": "装车/示范运行", "frontier_desc": "产业成熟：新建大项目/流域开发即前沿事件；常规事件靠 TRL9 权重压制（草案）",
        "metrics": [("年利用小时数", "h", "流域差异大，无统一参考（正式基线 null）")],
        "bottlenecks": [("hydro_flex", "水电灵活性与流域生态约束", "SECONDARY", "institutional_access_state")],
        "financing_anchor": "项目融资为主（草案 null 待登记）",
        "policy_hot": "流域规划与电价、抽蓄容量电价机制（草案）",
        "matrix": {"card_tech": ("—", ""), "card_validation": ("—", ""), "card_project": ("★", "大型水电/抽蓄项目"),
                   "card_product": ("—", ""), "card_enterprise": ("○", "水电资产重组"),
                   "card_production": ("○", "来水与发电量"), "card_supply": ("—", ""),
                   "card_financing": ("—", ""), "card_procurement": ("○", "机组招标"),
                   "card_talent": ("—", ""), "card_market": ("○", "水电电量交易"),
                   "card_policy": ("★", "流域规划/电价机制")},
    },
    {
        "id": "E03", "slug": "biomass_fuel", "name": "生物质燃料", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能源测|一次能源转化|燃料转化（热/电）|生物质燃料", "leaves": ["生物质燃料"],
        "priority": "覆盖建卡",
        "core": "生物质|生物燃料|生物柴油|生物甲烷|沼气|成型燃料|SAF|可持续航空燃料",
        "ext": "农林废弃物|秸秆|蔗渣|加氢植物油|HVO|燃料乙醇|生物质热电",
        "stage_words": "投产|并网|量产|认证|批次",
        "actors": "长青集团、伟明环保、海新能科、嘉澳环保（草案，待补充）",
        "scale_anchor": "生物柴油/SAF 万吨级产线为量级参考（草案）",
        "require": "生物质/生物燃料/SAF 词 + 指标（万吨/年、掺混比例、认证）",
        "confuse": [("氢基能源（D05）", "绿色油品若走生物质路线归本域；Power-to-Liquid 走氢基", "原料路线区分"),
                    ("环境治理（E18）", "垃圾焚烧发电归固废处理；农林生物质归本域", "原料属性")],
        "trl_routes": [("生物柴油/成型燃料/热电", "8-9", "成熟产业（草案）"),
                       ("SAF/生物甲烷", "5-7", "示范-早期商业（草案）"),
                       ("BECCS", "4-6", "示范段（草案）")],
        "frontier": "量产/定型", "frontier_desc": "SAF 与先进生物燃料量产线为焦点；常规热电成熟（草案）",
        "metrics": [("SAF/生物柴油产能", "万吨/年", "单线 10-50 万吨级参考（正式基线 null）")],
        "bottlenecks": [("bio_supply", "燃料供应链成本与原料收集", "CORE", "production_operation_state"),
                        ("beccs_econ", "BECCS 负排放经济性", "SECONDARY", "institutional_access_state")],
        "financing_anchor": "SAF 初创/项目融资亿元级（草案 null 待登记）",
        "policy_hot": "SAF 强制掺混政策、生物质发电补贴退坡（草案）",
        "matrix": {"card_tech": ("○", "转化工艺命题"), "card_validation": ("○", "掺烧/适航认证验证"),
                   "card_project": ("★", "生物燃料产线项目"), "card_product": ("○", "生物燃料产品批次"),
                   "card_enterprise": ("—", ""), "card_production": ("★", "产线运行与出货"),
                   "card_supply": ("○", "原料收储网络"), "card_financing": ("○", "SAF 赛道融资"),
                   "card_procurement": ("○", "航司 SAF 长协"), "card_talent": ("—", ""),
                   "card_market": ("○", "生物燃料价格价差"), "card_policy": ("★", "强制掺混/补贴")},
    },
    {
        "id": "E04", "slug": "fuel_cell", "name": "燃料电池", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能源测|二次能源利用|燃料电池", "leaves": ["燃料电池"],
        "priority": "近期待建",
        "core": "燃料电池|电堆|质子交换膜|PEMFC|膜电极|MEA|双极板|空压机|氢燃料电池",
        "ext": "额定功率|功率密度|铂载量|冷启动|车载系统|固定式发电|热电联供",
        "stage_words": "装车|示范运营|批量交付|万台|耐久",
        "actors": "亿华通、重塑能源、国鸿氢能、捷氢科技、未势能源、巴拉德、丰田（草案）",
        "scale_anchor": "电堆万台/年产线、车用系统 MW 级示范车队为量级参考（草案）",
        "require": "燃料电池/电堆/MEA 词 + 指标（kW/L、铂载量、寿命 h、装机 MW）",
        "confuse": [("氢基能源（D05）", "电解槽（制氢方向）在氢基能源域；燃料电池（用氢方向）归本域", "用能环节区分"),
                    ("热机（E07）", "氢内燃机是燃烧路线，归热机域；燃料电池是电化学路线", "能量转换原理")],
        "trl_routes": [("车用 PEMFC", "7-9", "商业化初期，万辆级示范运营（草案）"),
                       ("固定式发电/热电联供", "6-8", "示范-早期商业（草案）"),
                       ("SOFC", "5-7", "示范段（草案）")],
        "frontier": "量产/定型", "frontier_desc": "车用电堆量产线与成本下探为焦点；固定式场景打开中（草案）",
        "metrics": [("电堆额定功率密度", "kW/L", "PEM 电堆约 4-5（公开参考，正式基线 null）"),
                    ("铂载量", "g/kW", "约 0.3 量级（公开参考）"),
                    ("电堆寿命", "h", "车用 2-3 万（公开参考）")],
        "bottlenecks": [("fc_cost_pt", "铂载量与系统成本", "CORE", "product_model_state,financing_capital_state"),
                        ("fc_durability", "耐久与衰减", "SECONDARY", "engineering_validation_state")],
        "financing_anchor": "燃料电池企业股权轮 1-10 亿元（草案 null 待登记）",
        "policy_hot": "氢燃料电池车示范城市群政策、加氢站建设补贴（草案）",
        "matrix": {"card_tech": ("★", "MEA/非铂催化剂命题"), "card_validation": ("★", "车队示范耐久验证"),
                   "card_project": ("○", "产线/加氢站"), "card_product": ("★", "电堆/系统新品"),
                   "card_enterprise": ("○", "头部盈亏拐点"), "card_production": ("○", "产线出货爬坡"),
                   "card_supply": ("○", "质子膜/铂族约束"), "card_financing": ("○", "赛道融资"),
                   "card_procurement": ("★", "车企定点/示范车队采购"), "card_talent": ("○", "电堆核心团队流动"),
                   "card_market": ("○", "系统价格"), "card_policy": ("★", "示范城市群/加氢站")},
    },
    {
        "id": "E05", "slug": "electric_heating", "name": "电加热与热泵", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能源测|二次能源利用|电加热（热泵/电锅炉/直接电加热）", "leaves": ["热泵", "电锅炉", "直接电加热（电阻/电弧加热）"],
        "priority": "近期待建",
        "core": "热泵|工业热泵|高温热泵|电锅炉|电阻加热|电弧炉|电磁感应加热|电气化",
        "ext": "COP|制热温度|蒸汽热泵|余热式热泵|绿电制蒸汽|工业电气化",
        "stage_words": "投运|示范项目|替代改造|吨蒸汽",
        "actors": "美的工业技术、格力电器、丹佛斯、博世、西门子（草案，待补充）",
        "scale_anchor": "高温热泵单机 MWth 级、园区供热项目为量级参考（草案）",
        "require": "热泵/电锅炉/电加热词 + 指标（COP、供出温度 ℃、MWth、吨蒸汽/日）",
        "confuse": [("储热（E12）", "热泵产热+储热联合系统：热泵设备归本域，储热单元归储热域", "对象粒度"),
                    ("工业余热回收（E08）", "余热利用的热泵归余热域叙事；热泵本体产品发布归本域", "主导对象")],
        "trl_routes": [("中低温热泵/电锅炉", "8-9", "成熟产业（草案）"),
                       ("高温工业热泵（>150℃）", "6-8", "示范推广段（草案）"),
                       ("电弧/感应加热", "8-9", "成熟工艺（草案）")],
        "frontier": "量产/定型", "frontier_desc": "高温段（>150-200℃）工业热泵示范为焦点；常规段成熟（草案）",
        "metrics": [("COP（工况口径）", "-", "工业热泵约 2.5-4（公开参考，正式基线 null）"),
                    ("最高供出温度", "℃", "高温热泵 150-200+（公开参考）")],
        "bottlenecks": [("high_temp", "高温段工质与压缩机覆盖", "CORE", "product_model_state,engineering_validation_state"),
                        ("econ_tariff", "电价经济性（vs 燃气蒸汽）", "CORE", "institutional_access_state,market_industry_state")],
        "financing_anchor": "设备销售为主，股权轮少见（草案 null 待登记）",
        "policy_hot": "工业电气化改造补贴、绿电制蒸汽试点（草案）",
        "matrix": {"card_tech": ("○", "工质/压缩机命题"), "card_validation": ("★", "高温段工业示范验证"),
                   "card_project": ("○", "园区供热改造项目"), "card_product": ("★", "热泵/加热装备新品"),
                   "card_enterprise": ("—", ""), "card_production": ("—", ""),
                   "card_supply": ("—", ""), "card_financing": ("—", ""),
                   "card_procurement": ("★", "工业企业采购/招标"), "card_talent": ("—", ""),
                   "card_market": ("○", "设备价格"), "card_policy": ("★", "电气化补贴/绿电蒸汽")},
    },
    {
        "id": "E06", "slug": "cooling_electric_drive", "name": "制冷散热与电驱动", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能源测|二次能源利用（制冷散热技术/电驱动（电机））", "leaves": ["制冷散热技术", "电驱动（电机）"],
        "priority": "覆盖建卡",
        "core": "制冷|散热|液冷|冷板|浸没式冷却|数据中心散热|电机|电驱|永磁电机|能效",
        "ext": "机房空调|CDU|冷却塔|变频|IE5|轴向磁通|电驱动桥",
        "stage_words": "部署|交付|量产|批次",
        "actors": "英维克、高澜股份、申菱环境、美的楼宇科技、汇川技术（草案）",
        "scale_anchor": "数据中心液冷项目 MW 级散热功率为量级参考（草案）",
        "require": "液冷/散热/电机电驱词 + 指标（散热密度 W/cm²、PUE、能效等级、kW/kg）",
        "confuse": [("AI 算力（跨界关注）", "算力中心主体新闻归 AI 域外；其供电散热方案落本域/电网域", "主导对象")],
        "trl_routes": [("常规制冷/高效电机", "8-9", "成熟产业（草案）"),
                       ("数据中心液冷（冷板/浸没）", "6-8", "规模化部署段（草案）")],
        "frontier": "量产/定型", "frontier_desc": "高功率密度散热（AI 算力配套液冷）规模化部署为焦点（草案）",
        "metrics": [("数据中心 PUE", "-", "液冷可至 1.1-1.2（公开参考，正式基线 null）")],
        "bottlenecks": [("power_density", "高功率密度散热（W/机架）", "CORE", "product_model_state"),
                        ("energy_eff", "能效标准升级", "SECONDARY", "institutional_access_state")],
        "financing_anchor": "液冷赛道融资活跃（草案 null 待登记）",
        "policy_hot": "数据中心能效准入（PUE 限值）、电机能效标准（草案）",
        "matrix": {"card_tech": ("○", "两相流/工质命题"), "card_validation": ("○", "部署验证"),
                   "card_project": ("○", "液冷数据中心项目"), "card_product": ("★", "液冷/CDU/高效电机新品"),
                   "card_enterprise": ("—", ""), "card_production": ("—", ""),
                   "card_supply": ("—", ""), "card_financing": ("○", "液冷赛道融资"),
                   "card_procurement": ("★", "数据中心/主机厂采购"), "card_talent": ("—", ""),
                   "card_market": ("○", "设备竞争格局"), "card_policy": ("○", "能效准入")},
    },
    {
        "id": "E07", "slug": "heat_engine", "name": "热机（内燃/外燃）", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能源测|二次能源利用|热驱动（热机）（内燃机/外燃机）", "leaves": ["内燃机", "外燃机"],
        "priority": "覆盖建卡",
        "core": "内燃机|氢内燃机|氨内燃机|甲醇发动机|外燃机|斯特林|热机",
        "ext": "缸内直喷|点火|燃烧室|热效率|零碳燃料发动机",
        "stage_words": "点火|台架|样机|装车|示范",
        "actors": "潍柴动力、玉柴、康明斯、一汽解放、中国船舶（草案）",
        "scale_anchor": "kW/MW 级机组、车队/船队示范为量级参考（草案）",
        "require": "内燃机/外燃机/氢氨甲醇发动机词 + 指标（热效率 %、功率 kW）",
        "confuse": [("燃料电池（E04）", "电化学路线 vs 燃烧路线", "能量转换原理"),
                    ("火电掺烧（D10）", "电站锅炉掺烧归火电掺烧域；发动机缸内燃烧归本域", "应用载体")],
        "trl_routes": [("常规内燃机", "9", "成熟产业（草案）"),
                       ("氢/氨/甲醇内燃机", "4-6", "台架-装车示范段（草案）"),
                       ("外燃机/斯特林", "5-7", "特种应用示范（草案）")],
        "frontier": "中试/示范", "frontier_desc": "零碳燃料发动机装车/装船示范为焦点（草案）",
        "metrics": [("有效热效率", "%", "柴油机约 45-50 上限参考；氢内燃机 40+（公开参考，正式基线 null）")],
        "bottlenecks": [("combustion", "氨氢燃烧稳定性与排放（NOx/NH3 逃逸）", "CORE", "engineering_validation_state,technical_knowledge_change")],
        "financing_anchor": "以企业自研为主（草案 null 待登记）",
        "policy_hot": "零碳燃料发动机示范政策、船用燃料规范（草案）",
        "matrix": {"card_tech": ("★", "燃烧机理命题"), "card_validation": ("★", "台架/装车示范验证"),
                   "card_project": ("—", ""), "card_product": ("○", "新型号发动机"),
                   "card_enterprise": ("—", ""), "card_production": ("—", ""),
                   "card_supply": ("—", ""), "card_financing": ("—", ""),
                   "card_procurement": ("○", "车队/船东定点"), "card_talent": ("—", ""),
                   "card_market": ("—", ""), "card_policy": ("○", "船用燃料规范")},
    },
    {
        "id": "E08", "slug": "waste_heat_recovery", "name": "工业余热回收", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能源测|二次能源利用|工业余热回收", "leaves": ["工业余热回收"],
        "priority": "覆盖建卡",
        "core": "余热回收|余热发电|ORC|有机朗肯|余热锅炉|梯级利用|低温余热",
        "ext": "烟气余热|冲渣水|循环水余热|热泵提温|余热资产品位",
        "stage_words": "投运|改造完成|节能率",
        "actors": "西子洁能、中材节能、天壕环境、双良节能（草案）",
        "scale_anchor": "余热发电 MW 级、年节约 tce 为量级参考（草案）",
        "require": "余热/ORC/梯级利用词 + 指标（MW、年节气量、节能率 %）",
        "confuse": [("电加热与热泵（E05）", "余热热泵设备产品归 E05；余热利用工程项目叙事归本域", "主导对象")],
        "trl_routes": [("高温余热回收", "8-9", "成熟（草案）"),
                       ("低温余热/ORC", "6-8", "推广段（草案）")],
        "frontier": "量产/定型", "frontier_desc": "低温段余热经济性利用为焦点（草案）",
        "metrics": [("余热发电效率", "%", "ORC 低温段约 8-15（公开参考，正式基线 null）")],
        "bottlenecks": [("low_temp_econ", "低温余热经济性与品位", "CORE", "project_facility_state,market_industry_state")],
        "financing_anchor": "合同能源管理/项目融资（草案 null 待登记）",
        "policy_hot": "工业节能监察与改造补贴（草案）",
        "matrix": {"card_tech": ("○", "工质/换热命题"), "card_validation": ("○", "改造投运验证"),
                   "card_project": ("★", "余热利用改造项目"), "card_product": ("—", ""),
                   "card_enterprise": ("—", ""), "card_production": ("—", ""),
                   "card_supply": ("—", ""), "card_financing": ("—", ""),
                   "card_procurement": ("○", "EMC 采购"), "card_talent": ("—", ""),
                   "card_market": ("—", ""), "card_policy": ("○", "节能补贴")},
    },
    {
        "id": "E09", "slug": "aqueous_battery", "name": "水系电池", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能量存储|电化学储能|二次电池|传统蓄电池|水系", "leaves": ["水系"],
        "priority": "覆盖建卡",
        "core": "水系电池|水系锌基|锌离子|锌溴|水系电解液| aqueous",
        "ext": "锌负极|析氢|枝晶|水性电解质|安全电池",
        "stage_words": "中试|示范|样品",
        "actors": "初创团队为主（草案 null 待登记）",
        "scale_anchor": "中试 MWh 级为量级参考（草案）",
        "require": "水系/锌基电池词 + 指标（Wh/kg、循环次、Ah）",
        "confuse": [("锂电池（D02）", "有机体系 vs 水性体系", "电解液体系区分"),
                    ("液流电池（E11）", "静态水系 vs 流动电解液", "结构区分")],
        "trl_routes": [("水系锌基等", "3-5", "实验室-中试早期（草案）")],
        "frontier": "实验室样品/样机", "frontier_desc": "部分体系进入中试早期；循环与析氢为核心命题（草案）",
        "metrics": [("循环寿命", "次", "目标万次级（公开参考，正式基线 null）")],
        "bottlenecks": [("zinc_dendrite", "锌枝晶与析氢", "CORE", "technical_knowledge_change,engineering_validation_state")],
        "financing_anchor": "早期轮千万元级（草案 null 待登记）",
        "policy_hot": "本域暂无专门政策通道（草案）",
        "matrix": {"card_tech": ("★", "电解液/负极命题"), "card_validation": ("○", "中试验证"),
                   "card_project": ("—", ""), "card_product": ("○", "样品/中试产品"),
                   "card_enterprise": ("—", ""), "card_production": ("—", ""),
                   "card_supply": ("—", ""), "card_financing": ("○", "早期融资"),
                   "card_procurement": ("—", ""), "card_talent": ("—", ""),
                   "card_market": ("—", ""), "card_policy": ("—", "")},
    },
    {
        "id": "E10", "slug": "primary_supercap", "name": "一次电池与超级电容器", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能量存储|电化学储能（一次电池/超级电容器）", "leaves": ["一次电池", "超级电容器"],
        "priority": "覆盖建卡",
        "core": "超级电容|法拉电容|混合电容|一次电池|锂原电池|纽扣电池",
        "ext": "功率密度|循环次|秒级响应|能量密度 Wh/kg",
        "stage_words": "量产|交付|装车",
        "actors": "江海股份、奥威科技、今朝时代、亿纬锂能（草案）",
        "scale_anchor": "超电容产线千万支级、公交/轨交应用为量级参考（草案）",
        "require": "超级电容/一次电池词 + 指标（功率密度 kW/kg、循环 10 万次）",
        "confuse": [("锂电池（D02）", "可充电二次体系归锂电/钠电域；本域为非二次/功率型", "充放电属性")],
        "trl_routes": [("超级电容器", "7-8", "成熟产业，新型混合电容 5-7（草案）"),
                       ("一次电池", "9", "成熟产业（草案）")],
        "frontier": "量产/定型", "frontier_desc": "混合电容（电池型超电容）为性能焦点（草案）",
        "metrics": [("功率密度", "kW/kg", "超电容 5-10+（公开参考，正式基线 null）")],
        "bottlenecks": [("energy_density", "能量密度提升", "CORE", "product_model_state")],
        "financing_anchor": "成熟产业，股权轮少见（草案 null 待登记）",
        "policy_hot": "暂无专门政策通道（草案）",
        "matrix": {"card_tech": ("○", "电极材料命题"), "card_validation": ("○", "应用验证"),
                   "card_project": ("—", ""), "card_product": ("★", "超电容/一次电池新品"),
                   "card_enterprise": ("—", ""), "card_production": ("○", "产线出货"),
                   "card_supply": ("○", "活性炭/电解液"), "card_financing": ("—", ""),
                   "card_procurement": ("○", "轨交/电网采购"), "card_talent": ("—", ""),
                   "card_market": ("—", ""), "card_policy": ("—", "")},
    },
    {
        "id": "E11", "slug": "flow_battery", "name": "液流电池", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能量存储|电化学储能|二次电池|液流电池", "leaves": ["液流电池"],
        "priority": "近期待建",
        "core": "液流电池|全钒|钒液流|铁铬液流|锌溴液流|液流储能",
        "ext": "电解液|离子交换膜|电堆|电流密度|容量恢复",
        "stage_words": "并网|示范|百兆瓦时|交付",
        "actors": "大连融科、北京普能、上海电气、纬景储能（草案，待补充）",
        "scale_anchor": "100MW/400MWh 级示范为域量级参考（草案）",
        "require": "液流/全钒/铁铬词 + 指标（MW/MWh、能量效率 %、时长 h）",
        "confuse": [("储能系统（D03）", "系统集成/电站视角归储能系统域；液流电堆/电解液本体归本域", "对象粒度"),
                    ("水系电池（E09）", "静态水系 vs 流动电解液", "结构区分")],
        "trl_routes": [("全钒液流", "6-8", "100MW 级示范商运（草案）"),
                       ("铁铬/锌溴液流", "4-6", "示范段（草案）")],
        "frontier": "交付/客户验证", "frontier_desc": "百 MWh 级商业项目交付与成本下探为焦点（草案）",
        "metrics": [("系统能量效率", "%", "全钒约 70-78（公开参考，正式基线 null）"),
                    ("运行电流密度", "mA/cm²", "约 160-200 为高水平（公开参考）")],
        "bottlenecks": [("flow_cost", "初始投资与钒价联动", "CORE", "market_industry_state,financing_capital_state"),
                        ("membrane", "膜与电极成本", "SECONDARY", "product_model_state")],
        "financing_anchor": "液流赛道股权轮亿元级（草案 null 待登记）",
        "policy_hot": "长时储能容量补偿/示范名单（与储能系统域共用政策通道）（草案）",
        "matrix": {"card_tech": ("★", "电解液/膜命题"), "card_validation": ("★", "示范电站运行验证"),
                   "card_project": ("★", "液流储能项目"), "card_product": ("★", "电堆/系统新品"),
                   "card_enterprise": ("—", ""), "card_production": ("○", "产线出货"),
                   "card_supply": ("○", "钒原料供应"), "card_financing": ("○", "赛道融资"),
                   "card_procurement": ("★", "电网/开发商框采"), "card_talent": ("—", ""),
                   "card_market": ("○", "系统中标价"), "card_policy": ("★", "长时储能政策")},
    },
    {
        "id": "E12", "slug": "thermal_storage", "name": "储热技术", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能量存储|储热（水/油储热、熔盐储热、固态储热）", "leaves": ["水/油储热", "熔盐储热", "固态储热"],
        "priority": "近期待建",
        "core": "储热|熔盐|熔盐储热|固态储热|相变储热|显热储热|蒸汽储热",
        "ext": "储热介质|储罐|放热|蒸汽发生器|热泵+储热|工业蒸汽",
        "stage_words": "投运|供汽|示范|储热时长",
        "actors": "西子洁能、首航高科、上海电气（草案，待补充）",
        "scale_anchor": "百 MWh_th 级储热系统为量级参考（草案）",
        "require": "储热/熔盐/相变词 + 指标（MWh_th、供汽 t/h、储热时长 h、温度 ℃）",
        "confuse": [("光热（E01）", "光热电站配储整体归光热；独立储热系统/产品归本域", "对象粒度"),
                    ("电加热与热泵（E05）", "热泵产热归 E05；储热单元与供汽系统归本域", "对象粒度")],
        "trl_routes": [("熔盐储热", "6-8", "光热配储成熟、独立储热供汽示范推广（草案）"),
                       ("水/油显热", "8-9", "成熟（草案）"),
                       ("固态/相变", "4-6", "示范段（草案）")],
        "frontier": "交付/客户验证", "frontier_desc": "独立熔盐储热供汽（绿电+储热工业园区）示范为焦点（草案）",
        "metrics": [("储热容量", "MWh_th", "项目级 100-1000 参考区间（公开参考，正式基线 null）"),
                    ("放热温度", "℃", "熔盐 350-565 区间参考")],
        "bottlenecks": [("salt_material", "高温储热材料腐蚀与防凝", "CORE", "technical_knowledge_change,engineering_validation_state")],
        "financing_anchor": "项目/EPC 为主（草案 null 待登记）",
        "policy_hot": "长时储能（储热型）支持政策、工业绿电制蒸汽试点（草案）",
        "matrix": {"card_tech": ("★", "储热材料命题"), "card_validation": ("★", "储热供汽示范验证"),
                   "card_project": ("★", "储热项目"), "card_product": ("○", "储热装备"),
                   "card_enterprise": ("—", ""), "card_production": ("—", ""),
                   "card_supply": ("—", ""), "card_financing": ("—", ""),
                   "card_procurement": ("○", "园区供热采购"), "card_talent": ("—", ""),
                   "card_market": ("—", ""), "card_policy": ("○", "长时储能政策")},
    },
    {
        "id": "E13", "slug": "metal_energy_storage", "name": "金属储能", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能量存储|化学能|金属储能", "leaves": ["金属储能"],
        "priority": "覆盖建卡",
        "core": "金属储能|金属空气电池|铁空气|铝空气|金属氢化物储氢|储热合金",
        "ext": "可逆氧化还原|放电产物|能量载体",
        "stage_words": "样品|实验室|中试",
        "actors": "初创团队为主（草案 null 待登记）",
        "scale_anchor": "实验室-kWh 级（草案）",
        "require": "金属储能/金属空气词 + 指标（Wh/kg、循环次、效率 %）",
        "confuse": [("水系电池（E09）", "铁空气电池多为水系——按技术族归本域跟踪，差异登记", "技术族优先")],
        "trl_routes": [("金属空气（铁/铝空气）", "3-5", "实验室-早期中试（草案）")],
        "frontier": "实验室样品/样机", "frontier_desc": "可逆性与循环效率为核心命题（草案）",
        "metrics": [("能量效率", "%", "铁空气目标 40-50+（公开参考，正式基线 null）")],
        "bottlenecks": [("reversibility", "可逆循环效率", "CORE", "technical_knowledge_change")],
        "financing_anchor": "早期轮（草案 null 待登记）",
        "policy_hot": "暂无专门政策通道（草案）",
        "matrix": {"card_tech": ("★", "机理命题为主"), "card_validation": ("○", "样机验证"),
                   "card_project": ("—", ""), "card_product": ("—", ""),
                   "card_enterprise": ("—", ""), "card_production": ("—", ""),
                   "card_supply": ("—", ""), "card_financing": ("○", "早期融资"),
                   "card_procurement": ("—", ""), "card_talent": ("—", ""),
                   "card_market": ("—", ""), "card_policy": ("—", "")},
    },
    {
        "id": "E14", "slug": "mechanical_storage", "name": "机械储能（重力/飞轮）", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能量存储|机械能（重力储能、飞轮储能）", "leaves": ["重力储能", "飞轮储能"],
        "priority": "覆盖建卡",
        "core": "重力储能|飞轮储能|飞轮|机械储能|竖井储能",
        "ext": "重块|泵站|转速|rpm|秒级|毫秒级响应|磁悬浮",
        "stage_words": "并网|示范|投运",
        "actors": "中国天楹、沈阳微控、华驰动能（草案，待补充）",
        "scale_anchor": "重力 100MWh 级示范、飞轮 MW 级阵列（草案）",
        "require": "重力/飞轮储能词 + 指标（MW/MWh、响应时间）",
        "confuse": [("压缩空气（D08）", "同属机械储能大类但技术独立分域", "技术路线区分")],
        "trl_routes": [("飞轮储能", "6-8", "成熟产业，阵列化推广（草案）"),
                       ("重力储能", "3-5", "首批示范并网（草案）")],
        "frontier": "中试/示范", "frontier_desc": "重力储能首示范期为域焦点；飞轮已成熟产业化（草案）",
        "metrics": [("往返效率", "%", "飞轮 85-90+、重力目标 80+（公开参考，正式基线 null）")],
        "bottlenecks": [("grav_cost", "重力系统效率与选址经济性", "CORE", "project_facility_state,engineering_validation_state")],
        "financing_anchor": "示范项目融资为主（草案 null 待登记）",
        "policy_hot": "长时储能/新型储能示范名单（与储能域共用通道）（草案）",
        "matrix": {"card_tech": ("○", "系统方案命题"), "card_validation": ("★", "示范并网验证"),
                   "card_project": ("★", "重力/飞轮项目"), "card_product": ("○", "飞轮阵列产品"),
                   "card_enterprise": ("—", ""), "card_production": ("—", ""),
                   "card_supply": ("—", ""), "card_financing": ("○", "示范融资"),
                   "card_procurement": ("○", "电网框采"), "card_talent": ("—", ""),
                   "card_market": ("—", ""), "card_policy": ("○", "新型储能政策")},
    },
    {
        "id": "E15", "slug": "grid_vpp", "name": "电网技术与虚拟电厂", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能量分配与运输（电网相关技术/虚拟电厂与电力交易）", "leaves": ["电网相关技术", "虚拟电厂与电力交易"],
        "priority": "近期待建",
        # 2026-09-18 复核补丁：英文文献标题（voltage volatility/transmission expansion 等）并入判定词表；
        # 无歧义英文短语进 core（空正文文献按标题判域只认 core 命中）
        # 2026-09-19 v1.03：变压器/输变电设备为电网硬件主对象（变压器交货四年类瓶颈报道归本域）
        "core": "电网|特高压|柔性直流|构网型|虚拟电厂|VPP|电力交易|智能电网|配电网|变压器|输变电设备|power grid|electricity grid|smart grid|distribution network|microgrid|virtual power plant|transmission expansion|power transmission|electricity transmission|transmission network|transmission system|voltage volatility|voltage regulation|reactive power|grid flexibility|power system flexibility|grid decarbonization|park-level integrated energy|power transformer",
        "ext": "换流阀|SVG|聚合商|需求响应|现货市场|辅助服务|绿电直供|源网荷储|topological|energy management|integrated energy system|off-grid electrification",
        "stage_words": "投运|并网|挂网|上线|聚合|grid expansion",
        "actors": "国家电网、南方电网、国电南瑞、许继电气、朗新科技（草案）",
        "scale_anchor": "特高压工程 GW 级、VPP 聚合百 MW 级为量级参考（草案）",
        "require": "电网/柔直/虚拟电厂/交易词（中英）+ 指标（GW、聚合 MW、响应时长）；英文文献仅标题可用时按标题语义直接判定，不以指标缺失拒绝",
        "confuse": [("储能系统（D03）", "储能电站本体归储能域；并网/调度/市场机制叙事归本域", "主导对象")],
        "trl_routes": [("电网技术（柔直/构网型）", "7-9", "工程成熟，构网型示范推广（草案）"),
                       ("虚拟电厂/电力交易", "5-7", "示范-早期商业（草案）")],
        "frontier": "交付/客户验证", "frontier_desc": "VPP 规模化聚合入市与构网型设备批量部署为焦点（草案）",
        "metrics": [("VPP 聚合规模", "MW", "示范 100-1000MW 级参考（公开参考，正式基线 null）")],
        "bottlenecks": [("vpp_market", "聚合与市场价格机制", "CORE", "institutional_access_state,market_industry_state"),
                        ("grid_forming", "构网型变流与支撑能力", "SECONDARY", "product_model_state,engineering_validation_state")],
        "financing_anchor": "VPP/电力交易赛道融资活跃（草案 null 待登记）",
        "policy_hot": "电力现货市场规则、绿电直供/直连政策、虚拟电厂管理办法（草案）",
        "matrix": {"card_tech": ("○", "调度算法/构网命题"), "card_validation": ("★", "构网型/VPP 挂网验证"),
                   "card_project": ("★", "电网工程/VPP 平台"), "card_product": ("★", "构网型设备/平台产品"),
                   "card_enterprise": ("○", "电网设备商格局"), "card_production": ("—", ""),
                   "card_supply": ("○", "换流阀核心器件"), "card_financing": ("○", "VPP 赛道融资"),
                   "card_procurement": ("★", "电网设备招标"), "card_talent": ("—", ""),
                   "card_market": ("★", "电力市场价格机制"), "card_policy": ("★", "市场规则/直连政策")},
    },
    {
        "id": "E16", "slug": "energy_pipeline", "name": "能源管网（天然气/氢/油）", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能量分配与运输|能源载体管网（天然气管网/氢气管网/输油管道）", "leaves": ["天然气管网", "氢气管网", "输油管道"],
        "priority": "覆盖建卡",
        "core": "管网|天然气管网|氢气管网|输油管道|掺氢|纯氢管道|管道运输",
        "ext": "掺氢比例|氢脆|管材|压缩机组|互联互通|管网容量",
        "stage_words": "贯通|投产|试压|掺氢示范",
        "actors": "国家管网集团、中石化、中石油（草案）",
        "scale_anchor": "干线 km 级、掺氢比例 %（草案）",
        "require": "管网/管道/掺氢词 + 指标（km、掺氢比 %、输量）",
        "confuse": [("氢基能源（D05）", "制氢/用氢归氢域；输运环节归本域", "环节归属")],
        "trl_routes": [("天然气管网/输油", "9", "成熟基础设施（草案）"),
                       ("掺氢管道", "4-6", "示范段（草案）"),
                       ("纯氢管道", "3-5", "示范早期（草案）")],
        "frontier": "中试/示范", "frontier_desc": "掺氢/纯氢管输示范为域焦点（草案）",
        "metrics": [("掺氢比例", "%", "示范 3-20% 区间参考（公开参考，正式基线 null）")],
        "bottlenecks": [("h2_brittle", "氢脆与管材适应性", "CORE", "technical_knowledge_change,engineering_validation_state")],
        "financing_anchor": "基建投资为主（草案 null 待登记）",
        "policy_hot": "掺氢示范政策、氢能管网规划（草案）",
        "matrix": {"card_tech": ("○", "管材/氢脆命题"), "card_validation": ("★", "掺氢/纯氢管输示范"),
                   "card_project": ("★", "管网工程"), "card_product": ("—", ""),
                   "card_enterprise": ("—", ""), "card_production": ("—", ""),
                   "card_supply": ("—", ""), "card_financing": ("—", ""),
                   "card_procurement": ("○", "管材/压缩机组招标"), "card_talent": ("—", ""),
                   "card_market": ("○", "管输费"), "card_policy": ("★", "管网规划/掺氢政策")},
    },
    # ================= 物质循环（8 域） =================
    {
        "id": "E17", "slug": "material_recycling", "name": "物质回收与梯次利用", "branch": "物质循环",
        "tree": "零碳产业|物质循环|资源回收利用与排放治理（物质回收/梯次利用）", "leaves": ["物质回收", "梯次利用"],
        "priority": "近期待建",
        "core": "回收|电池回收|梯次利用|退役动力电池|再生锂|湿法回收|黑粉",
        "ext": "破碎|分选|提锂率|碳酸锂|再生材料|闭环回收|余能检测",
        "stage_words": "投产|达产|批量|退役潮",
        "actors": "格林美、邦普循环（宁德时代）、华友钴业、赣锋循环、天奇股份（草案）",
        "scale_anchor": "回收产线万吨级黑粉/年、梯次 MWh 级项目（草案）",
        "require": "回收/梯次词 + 指标（万吨/年、回收率 %、tCO2 减排）",
        "confuse": [("锂电池（D02）", "电芯制造归锂电域；退役电池资源化归本域", "生命周期环节")],
        "trl_routes": [("湿法回收", "8-9", "成熟产业（草案）"),
                       ("梯次利用", "5-7", "示范-早期商业（草案）"),
                       ("直接回收/正极再生", "3-5", "实验室-中试（草案）")],
        "frontier": "量产/定型", "frontier_desc": "退役潮下的规模化盈利模型与闭环体系为焦点（草案）",
        "metrics": [("锂回收率", "%", "国标要求≥90，先进 95+（公开参考，正式基线 null）"),
                    ("镍钴回收率", "%", "≥98 先进参考")],
        "bottlenecks": [("black_powder", "黑粉品位与回收率", "CORE", "production_operation_state"),
                        ("recycle_econ", "经济性（碳酸锂价联动）", "CORE", "market_industry_state"),
                        ("echelon_safety", "梯次安全与一致性", "SECONDARY", "engineering_validation_state")],
        "financing_anchor": "回收项目融资亿元级（草案 null 待登记）",
        "policy_hot": "动力电池回收白名单与生产者责任延伸、再生材料含量要求（草案）",
        "matrix": {"card_tech": ("○", "直接回收工艺命题"), "card_validation": ("○", "梯次示范验证"),
                   "card_project": ("★", "回收产线项目"), "card_product": ("—", ""),
                   "card_enterprise": ("○", "白名单格局"), "card_production": ("★", "产线达产与回收率"),
                   "card_supply": ("★", "退役电池货源网络"), "card_financing": ("○", "项目融资"),
                   "card_procurement": ("○", "车企闭环协议"), "card_talent": ("—", ""),
                   "card_market": ("★", "再生料价格价差"), "card_policy": ("★", "白名单/再生含量")},
    },
    {
        "id": "E18", "slug": "environmental_treatment", "name": "环境治理（固废/污水）", "branch": "物质循环",
        "tree": "零碳产业|物质循环|资源回收利用与排放治理（固废处理/污水处理）", "leaves": ["固废处理", "污水处理"],
        "priority": "覆盖建卡",
        "core": "固废|垃圾焚烧|危废|污水处理|水处理|中水回用|资源化",
        "ext": "飞灰|渗滤液|提锂|沼气|污泥|膜处理|零排放",
        "stage_words": "投运|扩建|达标|验收",
        "actors": "光大环境、瀚蓝环境、北控水务、首创环保（草案）",
        "scale_anchor": "焚烧厂吨/日千吨级、污水厂万吨级日处理（草案）",
        "require": "固废/污水/焚烧词 + 指标（t/d、万吨/日、资源化率 %）",
        "confuse": [("物质回收（E17）", "电池回收归 E17；市政固废污水归本域", "对象属性"),
                    ("生物质（E03）", "农林生物质燃料归 E03；垃圾焚烧发电归本域", "原料属性")],
        "trl_routes": [("焚烧/污水主体工艺", "9", "成熟产业（草案）"),
                       ("资源化新工艺（盐湖提锂耦合/沼气提纯）", "5-7", "示范段（草案）")],
        "frontier": "量产/定型", "frontier_desc": "资源化率与降耗增效为焦点；主体工艺成熟（草案）",
        "metrics": [("资源化率", "%", "分对象差异大（公开参考，正式基线 null）")],
        "bottlenecks": [("resource_rate", "资源化率与盈利模型", "CORE", "production_operation_state,institutional_access_state")],
        "financing_anchor": "特许经营/BOT 为主（草案 null 待登记）",
        "policy_hot": "垃圾焚烧补贴退坡、污水资源化利用政策（草案）",
        "matrix": {"card_tech": ("○", "资源化工艺命题"), "card_validation": ("○", "新工艺示范"),
                   "card_project": ("★", "处理设施项目"), "card_product": ("—", ""),
                   "card_enterprise": ("○", "运营商格局"), "card_production": ("★", "设施运行数据"),
                   "card_supply": ("—", ""), "card_financing": ("—", ""),
                   "card_procurement": ("—", ""), "card_talent": ("—", ""),
                   "card_market": ("—", ""), "card_policy": ("★", "补贴/资源化政策")},
    },
    {
        "id": "E19", "slug": "resource_extraction", "name": "资源勘探与开采", "branch": "物质循环",
        "tree": "零碳产业|物质循环|资源获取（勘探技术/开采技术/种植养殖技术）", "leaves": ["勘探技术", "开采技术", "种植养殖技术"],
        "priority": "覆盖建卡",
        "core": "勘探|勘查|采矿|开采|选矿|绿色矿山|原矿|品位",
        "ext": "钻探|物探|采选|无废开采|充填|矿山修复",
        "stage_words": "探获|备案|投产|达产",
        "actors": "紫金矿业、中国五矿、洛阳钼业（草案）",
        "scale_anchor": "矿山项目按金属品种分列（草案 null 待登记）",
        "require": "勘探/开采/矿山词 + 指标（资源量、品位 %、产能）；T15 资源体系类新闻主通道",
        "confuse": [("具体金属域", "矿端资源新闻在对应金属域（锂→D02 链、铝铜→E22）计分，本域收通用技术叙事", "主导对象")],
        "trl_routes": [("常规勘探开采", "9", "成熟（草案）"),
                       ("绿色勘查/无废开采", "6-8", "推广段（草案）")],
        "frontier": "量产/定型", "frontier_desc": "绿色化与智能化开采为焦点（草案）",
        "metrics": [], "bottlenecks": [("green_mining", "绿色开采与生态约束", "SECONDARY", "institutional_access_state")],
        "financing_anchor": "矿业项目融资（草案 null 待登记）",
        "policy_hot": "矿产资源规划、绿色矿山名录（草案）",
        "matrix": {"card_tech": ("○", "勘探技术命题"), "card_validation": ("—", ""),
                   "card_project": ("★", "矿山开发项目"), "card_product": ("—", ""),
                   "card_enterprise": ("—", ""), "card_production": ("★", "采选运行"),
                   "card_supply": ("—", ""), "card_financing": ("○", "矿业融资"),
                   "card_procurement": ("—", ""), "card_talent": ("—", ""),
                   "card_market": ("—", ""), "card_policy": ("○", "矿权/绿色矿山")},
    },
    {
        "id": "E20", "slug": "green_chemicals", "name": "绿色化工（平台化学品）", "branch": "物质循环",
        "tree": "零碳产业|物质循环|资源加工|有机物|平台化工品（合成气平台/乙烯丙烯丁二烯/苯甲苯二甲苯）", "leaves": ["合成气平台", "乙烯/丙烯/丁二烯", "苯/甲苯/二甲苯"],
        "priority": "覆盖建卡",
        "core": "绿色化工|生物基|CO2 制化学品|电催化|合成气|生物基烯烃|生物基芳烃",
        "ext": "费托|加氢|催化剂|低碳烯烃|芳烃|CCU|循环化工",
        "stage_words": "中试|示范线|投产|批次",
        "actors": "中石化、宝丰能源、华鲁恒升（草案）",
        "scale_anchor": "示范线千吨-万吨级、商业线十万吨级（草案）",
        "require": "生物基/CO2 制/绿色合成气词 + 指标（万吨/年、收率、碳强度）",
        "confuse": [("氢基能源（D05）", "绿甲醇/绿氨（燃料视角）挂氢基能源域（树中双视角，已登记）；本域收非燃料平台化学品", "双视角挂载"),
                    ("CCUS（D12）", "捕集环节归 CCUS；CO2 化学利用归本域", "环节归属")],
        "trl_routes": [("绿色合成气/生物基平台", "5-7", "示范段（草案）"),
                       ("CO2 制化学品（电催化/热催化）", "3-5", "实验室-中试（草案）"),
                       ("生物基烯烃/芳烃", "4-6", "中试-示范（草案）")],
        "frontier": "中试/示范", "frontier_desc": "万吨级生物基/CO2 基示范线为焦点（草案）",
        "metrics": [("示范产能", "万吨/年", "千吨-万吨级示范参考（公开参考，正式基线 null）")],
        "bottlenecks": [("green_cost", "绿氢/生物质成本传导", "CORE", "financing_capital_state,market_industry_state"),
                        ("catalyst", "催化剂活性选择性", "SECONDARY", "technical_knowledge_change")],
        "financing_anchor": "示范项目/企业股权亿元级（草案 null 待登记）",
        "policy_hot": "CCU 示范补贴、生物基材料推广政策（草案）",
        "matrix": {"card_tech": ("★", "催化剂/电催化命题"), "card_validation": ("★", "中试/示范线验证"),
                   "card_project": ("★", "示范线项目"), "card_product": ("○", "生物基产品批次"),
                   "card_enterprise": ("—", ""), "card_production": ("○", "示范线运行"),
                   "card_supply": ("—", ""), "card_financing": ("○", "示范融资"),
                   "card_procurement": ("○", "品牌商承购协议"), "card_talent": ("—", ""),
                   "card_market": ("○", "绿色溢价"), "card_policy": ("★", "CCU/生物基政策")},
    },
    {
        "id": "E21", "slug": "polymer_materials", "name": "塑料橡胶纤维", "branch": "物质循环",
        "tree": "零碳产业|物质循环|资源加工|有机物|大宗化工产品（塑料/橡胶/纤维）", "leaves": ["塑料", "橡胶", "纤维"],
        "priority": "覆盖建卡",
        "core": "再生塑料|化学回收|物理回收|生物基塑料|可降解|再生纤维|再生橡胶",
        "ext": "rPET|解聚|单体回收|食品级再生|改性",
        "stage_words": "投产|批次|认证|食品级",
        "actors": "金发科技、英科再生、三联虹普（草案）",
        "scale_anchor": "再生造粒万吨-十万吨级产线（草案）",
        "require": "再生塑料/化学回收/生物基词 + 指标（万吨/年、再生含量 %）",
        "confuse": [("绿色化工（E20）", "单体级平台化学品归 E20；聚合物材料归本域", "产业链层级")],
        "trl_routes": [("物理回收", "8-9", "成熟产业（草案）"),
                       ("化学回收（解聚/热解）", "4-6", "中试-示范（草案）"),
                       ("生物基聚合物", "5-7", "示范-早期商业（草案）")],
        "frontier": "量产/定型", "frontier_desc": "化学回收与食品级再生为焦点（草案）",
        "metrics": [("再生含量", "%", "品牌目标 25-50% 参考区间（公开参考，正式基线 null）")],
        "bottlenecks": [("chem_recycle", "化学回收解聚选择性与成本", "CORE", "technical_knowledge_change,project_facility_state"),
                        ("quality_keep", "再生料性能保持", "SECONDARY", "product_model_state")],
        "financing_anchor": "回收产线项目融资（草案 null 待登记）",
        "policy_hot": "再生含量强制要求、塑料污染治理政策（草案）",
        "matrix": {"card_tech": ("○", "解聚工艺命题"), "card_validation": ("○", "食品级认证验证"),
                   "card_project": ("★", "回收产线项目"), "card_product": ("○", "再生料产品"),
                   "card_enterprise": ("—", ""), "card_production": ("★", "产线运行"),
                   "card_supply": ("○", "废塑料货源"), "card_financing": ("—", ""),
                   "card_procurement": ("★", "品牌商承购"), "card_talent": ("—", ""),
                   "card_market": ("○", "再生料价差"), "card_policy": ("★", "再生含量政策")},
    },
    {
        "id": "E22", "slug": "nonferrous_metals", "name": "有色金属脱碳（铝/铜/稀土）", "branch": "物质循环",
        "tree": "零碳产业|物质循环|资源加工|无机物|金属（铝业/铜业/稀土产业）", "leaves": ["铝业", "铜业", "稀土产业"],
        "priority": "覆盖建卡",
        "core": "铝业|电解铝|惰性阳极|绿电铝|铜业|再生铜|稀土|绿色分离",
        "ext": "原铝|再生铝|铜冶炼|稀土萃取分离|碳排放基准",
        "stage_words": "投产|示范线|技改|达产",
        "actors": "中国铝业、云铝股份、江西铜业、紫金矿业、北方稀土（草案）",
        "scale_anchor": "电解铝产线百万吨级、再生铝十万吨级（草案）",
        "require": "铝/铜/稀土冶炼词 + 指标（万吨、再生比例 %、电耗 kWh/t）",
        "confuse": [("钢铁（D09）", "黑色金属归钢铁域；本域为有色（铝铜稀土）", "金属品种")],
        "trl_routes": [("再生铜铝", "8-9", "成熟（草案）"),
                       ("铝惰性阳极", "3-5", "实验室-中试（草案）"),
                       ("稀土绿色分离", "5-7", "推广段（草案）")],
        "frontier": "中试/示范", "frontier_desc": "惰性阳极（原铝脱碳焦点）中试早期；再生金属成熟（草案）",
        "metrics": [("电解铝电耗", "kWh/t", "约 13000-13500（公开参考，正式基线 null）")],
        "bottlenecks": [("inert_anode", "惰性阳极工程化", "CORE", "engineering_validation_state,technical_knowledge_change"),
                        ("scrap_grade", "再生金属品位与货源", "SECONDARY", "supply_network_state")],
        "financing_anchor": "技改/项目融资为主（草案 null 待登记）",
        "policy_hot": "电解铝能效约束与产能置换、碳市场纳入（草案）",
        "matrix": {"card_tech": ("★", "惰性阳极材料命题"), "card_validation": ("★", "惰性阳极中试验证"),
                   "card_project": ("★", "冶炼/再生项目"), "card_product": ("—", ""),
                   "card_enterprise": ("○", "巨头战略调整"), "card_production": ("★", "冶炼运行数据"),
                   "card_supply": ("○", "废杂金属货源"), "card_financing": ("—", ""),
                   "card_procurement": ("—", ""), "card_talent": ("—", ""),
                   "card_market": ("★", "金属价格/绿电铝溢价"), "card_policy": ("★", "能效约束/碳市场")},
    },
    {
        "id": "E23", "slug": "glass_ceramics", "name": "玻璃陶瓷", "branch": "物质循环",
        "tree": "零碳产业|物质循环|资源加工|无机物|非金属（玻璃/陶瓷）", "leaves": ["玻璃", "陶瓷"],
        "priority": "覆盖建卡",
        "core": "玻璃|浮法玻璃|电熔|氢窑|陶瓷|建筑陶瓷|电窑",
        "ext": "熔窑|全氧燃烧|电助熔|窑炉改造|光伏玻璃",
        "stage_words": "点火|投产|技改|冷修",
        "actors": "旗滨集团、信义玻璃、中国建材（凯盛）、科达制造（草案）",
        "scale_anchor": "浮法线千吨级日熔量（草案）",
        "require": "玻璃/陶瓷窑炉词 + 指标（t/d 熔量、燃料替代比例、电耗）",
        "confuse": [("水泥（D10）", "水泥窑归水泥域；玻璃陶瓷窑归本域", "品种区分")],
        "trl_routes": [("常规窑炉", "9", "成熟（草案）"),
                       ("电助熔/全氧燃烧", "7-8", "推广段（草案）"),
                       ("氢窑/全电熔", "4-6", "示范段（草案）")],
        "frontier": "中试/示范", "frontier_desc": "窑炉高温电气化（氢窑/全电熔）示范为焦点（草案）",
        "metrics": [("窑炉替代燃料比例", "%", "掺氢/电助熔 3-30% 示范区间（公开参考，正式基线 null）")],
        "bottlenecks": [("furnace_elec", "窑炉高温电气化", "CORE", "engineering_validation_state,project_facility_state")],
        "financing_anchor": "产线技改投资为主（草案 null 待登记）",
        "policy_hot": "建材行业超低排放改造、能效标杆政策（草案）",
        "matrix": {"card_tech": ("○", "耐火材料/电熔命题"), "card_validation": ("★", "氢窑/电熔示范"),
                   "card_project": ("★", "产线建设/技改"), "card_product": ("—", ""),
                   "card_enterprise": ("—", ""), "card_production": ("★", "产线运行"),
                   "card_supply": ("—", ""), "card_financing": ("—", ""),
                   "card_procurement": ("—", ""), "card_talent": ("—", ""),
                   "card_market": ("—", ""), "card_policy": ("★", "超低排放政策")},
    },
    {
        "id": "E24", "slug": "inorganic_chemicals", "name": "无机化工（酸/碱/尿素）", "branch": "物质循环",
        "tree": "零碳产业|物质循环|资源加工|无机物|无机化工（酸/碱/尿素）", "leaves": ["酸", "碱", "尿素"],
        "priority": "覆盖建卡",
        "core": "氯碱|烧碱|纯碱|硫酸|绿尿素|电催化制酸碱",
        "ext": "电解|离子膜|绿电氯碱|合成氨-尿素|联碱",
        "stage_words": "投产|技改|达产",
        "actors": "中盐化工、万华化学、远兴能源（草案）",
        "scale_anchor": "氯碱产线百万吨级（草案）",
        "require": "酸碱/氯碱/尿素词 + 指标（万吨、电耗、绿电比例）",
        "confuse": [("氢基能源（D05）", "绿氨归氢基能源；以绿氨制尿素的产品环节归本域", "产业链层级")],
        "trl_routes": [("氯碱/纯碱/硫酸主体", "9", "成熟（草案）"),
                       ("绿电灵活氯碱（负荷侧）", "5-7", "示范段（草案）"),
                       ("绿尿素", "4-6", "依赖绿氨成本（草案）")],
        "frontier": "中试/示范", "frontier_desc": "绿电耦合波动性负荷与绿尿素为焦点（草案）",
        "metrics": [("绿电比例", "%", "示范 10-30% 参考（公开参考，正式基线 null）")],
        "bottlenecks": [("flex_load", "电解负荷绿电波动适应", "CORE", "engineering_validation_state,institutional_access_state")],
        "financing_anchor": "技改/项目投资（草案 null 待登记）",
        "policy_hot": "氯碱行业能效约束、绿电交易政策（草案）",
        "matrix": {"card_tech": ("○", "电催化命题"), "card_validation": ("○", "绿电耦合示范"),
                   "card_project": ("★", "产线技改项目"), "card_product": ("—", ""),
                   "card_enterprise": ("—", ""), "card_production": ("★", "产线运行"),
                   "card_supply": ("—", ""), "card_financing": ("—", ""),
                   "card_procurement": ("—", ""), "card_talent": ("—", ""),
                   "card_market": ("○", "产品价格"), "card_policy": ("○", "能效约束")},
    },
    {
        # 2026-09-18 用户新增域：碳市场及温室气体监测（文献树无此叶，按扩展域登记）
        "id": "E25", "slug": "carbon_market_ghg_monitoring", "name": "碳市场与温室气体监测", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能量分配与运输（碳市场与温室气体监测）", "leaves": ["碳市场与温室气体监测"],
        "priority": "本轮新增·用户指定",
        "core": "碳市场|碳交易|碳排放权交易|碳配额|碳价|碳关税|CBAM|CCER|绿证|绿色电力证书|碳排放双控|双控考核|碳排放考核|能耗双控|温室气体排放报告|碳排放总量和强度|carbon market|carbon trading|carbon emission trading|emissions trading|cap-and-trade|carbon allowance|carbon permit|carbon emission optimization",
        "ext": "温室气体|GHG|温室气体监测|碳监测|碳核算|碳足迹|碳排放监测|碳排放核算|MRV|碳汇|碳泄漏|配额拍卖|履约|清缴|green certificate|carbon footprint|carbon pricing|clean energy investment|carbon management|emissions reduction",
        "stage_words": "开市|上线交易|扩容|纳入|履约|清缴|启动",
        "actors": "欧盟委员会、生态环境部、上海环交所、广州碳排放权交易所、北京绿色交易所（草案）",
        "scale_anchor": "全国碳市场年覆盖排放约 52 亿吨、EU ETS 为国际量级参考（草案）",
        "require": "碳市场/交易/监测机制词（中英）+ 制度动作或量化口径（配额、价格、tCO2、亿吨）；文献仅标题可用时按标题语义判定",
        "confuse": [("CCUS（D12）", "碳捕集技术本体归 CCUS；市场机制与监测归本域", "主导对象"),
                    ("电网技术与虚拟电厂（E15）", "电力交易/绿电交易归 E15；碳配额与碳市场机制归本域", "交易客体"),
                    ("政策与战略（T19）", "碳政策文件的类型仍是政策；域按主题归本域，类型与域分层", "类型域分层")],
        "trl_routes": [("碳市场与碳交易机制", "8-9", "EU ETS/全国碳市场已运行（草案）"),
                       ("温室气体监测与核算（MRV）", "6-8", "在线监测/卫星反演推广中（草案）")],
        "frontier": "规模化", "frontier_desc": "碳市场扩围纳入新行业、CBAM 实施与 MRV 监测体系完善为焦点（草案）",
        "metrics": [("碳市场覆盖排放量", "亿吨CO2/年", "全国碳市场约 52 亿吨（公开参考，正式基线 null）"),
                    ("碳价", "元/吨CO2", "全国市场数十元、EU ETS 数十欧元量级（公开参考，正式基线 null）")],
        "bottlenecks": [("carbon_pricing", "碳定价与配额机制", "CORE", "institutional_access_state,market_industry_state"),
                        ("ghg_mrv", "温室气体监测核算（MRV）", "SECONDARY", "indicator_state,engineering_validation_state")],
        "financing_anchor": "碳管理/碳监测 SaaS 与监测装备赛道（草案 null 待登记）",
        "policy_hot": "全国碳市场扩围、CBAM 过渡期结束、产品碳足迹管理体系（草案）",
        "matrix": {"card_tech": ("○", "碳核算/监测方法命题"), "card_validation": ("★", "MRV 监测验证"),
                   "card_project": ("○", "碳市场基础设施/监测网络"), "card_product": ("★", "碳监测设备/碳管理平台"),
                   "card_enterprise": ("—", ""), "card_production": ("—", ""),
                   "card_supply": ("—", ""), "card_financing": ("○", "碳管理赛道融资"),
                   "card_procurement": ("—", ""), "card_talent": ("—", ""),
                   "card_market": ("★", "碳价/配额交易动态"), "card_policy": ("★", "碳市场规则/扩围政策")},
    },
    {
        # 2026-09-19 用户新增域（反馈 8d：我国首个二氧化碳地热能项目投产被判“其他发电技术+T23 低”）：
        # 中深层地热/超临界CO2取热是稳定的一次能源供热路线，按内容新增专属域。
        "id": "E26", "slug": "geothermal_utilization", "name": "地热能利用", "branch": "能量转化",
        "tree": "零碳产业|能量转化|能源侧|一次能源转化（地热能利用）", "leaves": ["地热能利用"],
        "priority": "本轮新增·按内容判域",
        "core": "地热能|地热|干热岩|中深层地热|浅层地热|超临界二氧化碳|地热供暖|地热发电|geothermal|enhanced geothermal|EGS|supercritical CO2",
        "ext": "取热|换热井|同轴套管|地热井|梯级利用|地源热泵|闭式取热|ground-source heat pump",
        "stage_words": "投产|投运|建成|供暖季|并网发电|开工",
        "actors": "中国石化、中石油、华能、西安热工院、地大（草案）",
        "scale_anchor": "我国地热供暖面积数亿平方米量级（公开参考，正式基线 null）",
        "require": "地热/干热岩/超临界CO2取热词（中英）+ 供热或发电对象；二氧化碳作循环介质时按取热工艺归本域，不归 CCUS",
        "confuse": [("CCUS（D12）", "碳捕集封存归 D12；CO2 作地热循环工质是取热工艺，归本域", "二氧化碳角色"),
                    ("其他发电技术（GT10）", "GT10 为发电技术兜底叶；地热已有专属域后优先本域", "专属优先"),
                    ("热泵（E20 建筑脱碳侧）", "地源热泵建筑应用以建筑能效为主对象时归建筑侧，电站/取热工程归本域", "主对象")],
        "trl_routes": [("中深层地热闭式取热", "6-8", "首个示范项目投产（草案）"),
                       ("干热岩/EGS", "4-6", "试验阶段（草案）"),
                       ("地热发电", "7-9", "西藏羊八井等运行多年（草案）")],
        "frontier": "规模化", "frontier_desc": "闭式取热降低取水与回灌约束、干热岩压裂造储是焦点（草案）",
        "metrics": [("供暖面积", "万平方米", "示范项目 1.8 万 m² 量级（公开参考，正式基线 null）"),
                    ("取热深度", "米", "中深层 2000–3000 m 量级（公开参考，正式基线 null）")],
        "bottlenecks": [("geothermal_drilling", "钻探与造储成本", "CORE", "engineering_validation_state,market_industry_state"),
                        ("closed_loop_uptake", "闭式取热换热效率", "SECONDARY", "indicator_state,engineering_validation_state")],
        "financing_anchor": "地热供暖与钻井服务赛道（草案 null 待登记）",
        "policy_hot": "地热能纳入可再生能源供暖规划、干热岩示范（草案）",
        "matrix": {"card_tech": ("★", "取热工质/造储命题"), "card_validation": ("○", "换热效率验证"),
                   "card_project": ("★", "取热/供暖示范工程"), "card_product": ("○", "地热装备/工质"),
                   "card_enterprise": ("—", ""), "card_production": ("★", "供暖季运行"),
                   "card_supply": ("—", ""), "card_financing": ("○", "地热赛道融资"),
                   "card_procurement": ("—", ""), "card_talent": ("—", ""),
                   "card_market": ("—", ""), "card_policy": ("○", "地热规划")},
    },
]

# 叶 → 新建域 反查表（构建用）
EXPAND_LEAF_TO_DOMAIN = {}
for _d in EXPAND_DOMAINS:
    for _lf in _d["leaves"]:
        EXPAND_LEAF_TO_DOMAIN[_lf] = _d["id"]
